logging:
  level:
    root: WARN
    ru.tbcarus.spendingsb: DEBUG
  file:
    name: log/spendinglog.log
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{0} [%file:%line] %msg%n"

spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/spending-sb
    username: postgres
    password: postgres
  sql:
    init:
      mode: never
      schema-locations: classpath*:initDB.sql
      data-locations: classpath*:populateDB.sql
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  security:
    user:
      name: user
      password: pass

server:
  servlet:
    context-path: /spending

lombok:
  anyConstructor:
    addConstructorProperties: true


